# Generated by Django 4.2.13 on 2024-05-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_login_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='register_date',
        ),
    ]
